version: '3'

services:
  app:
    image: hackathon2023-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app
    restart: always
    volumes:
      - .:/app
    command: python main.py
    ports:
      - "80:80"

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - - ./data:/data 
volumes:
  mysql-data:
