name: Deploy to s3

on:
  push:
    branches: [main, feature/cicd]

  workflow_dispatch:

env:
  AWS_REGION: "ap-northeast-1"

jobs:
  build-deploy:
    runs-on: ubuntu-22.04

    # ロールだけでAWSログインできるやつ．
    # permissions:
    #   id-token: write
    #   contents: read

    steps:
      - uses: actions/checkout@v3

      - name: decode secrets file .env
        env:
          DOTEND_ENCODE: ${{ secrets.TEST_DOTENV }}

        run: |
          echo $DOTEND_ENCODE | base64 --decode > .env

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-session-name: github-actions-deploy-session
          aws-region: ${{ env.AWS_REGION }}

      - name: login to aws ecr
        run: |
          aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_URL }}

      - name: build docker image
        run: |
          docker build -t hackathon2023-winter-dd-backend .

      - name: add tag
        run: |
          docker tag hackathon2023-winter-dd-backend:latest ${{ secrets.ECR_URL }}/hackathon2023-winter-dd-backend:latest

      - name: push image
        run: |
          docker push ${{ secrets.ECR_URL }}/hackathon2023-winter-dd-backend:latest

      # キャッシュパージ
      # - name: clear cache
      #   run: |
      #     aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
